### ISSUE TITLE
Java code style nonobservance

### ISSUE THREAD

**Issue by valevaty98** [Shvingelskiy/Exchange-rates#5]
1. You should follow the ordering of import statements. Also the imports should be alphabetical and separated by blank line between groups.
2. Change the structure of the project. There are folders(packages) with the same name and their names don't reflect relation to the project (e. g. src/app/src/main/java/com/example/user/myfirstsapplication).
3. There are many commented code blocks and excess blank lines.
4. Every variable declaration (field or local) declares only one variable: declarations such as 
'String titleTest1 = "Hello", titleTest2 = "World", titleTest3 = "!!!";' are not used.
5. Use more meaningful names (e.g. title1, number1, number2, v cause misunderstandings).
6. Each switch statement should includes a default statement group, even if it contains no code. In your case, SecondActivity.java contains case-statement without default section.
7. This isn't acceptable (you should write this either in one line or with braces):
<code>
    else

        return false;
</code>

More information: [Java (Android)](https://source.android.com/setup/contribute/code-style).

**Comment by Shvingelskiy** [comment]
Done!
